/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedistribuida.vista;

import basedistribuida.broadcast.BroadcastUtils;
import basedistribuida.coordinator.Coordinador;
import basedistribuida.model.Estado;
import basedistribuida.model.Municipio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author iovanny
 */
public class Editarmunicipio extends javax.swing.JFrame {

    private Municipio municipio;
    private Municipios municipiosFrame;
    private Coordinador coordinador;
    private List<Estado> listaEstados;

    /**
     * Creates new form Agregarpersona
     */
    public Editarmunicipio(Municipio municipio, Municipios municipiosFrame) {
        this.municipio = municipio;
        this.municipiosFrame = municipiosFrame;
        initComponents();
        init();
    }

    private void init() {
        //Cargar estados
        coordinador = new Coordinador();
        listaEstados = coordinador.obtenerEstados();
        
        if (!listaEstados.isEmpty()) {
            ArrayList<String> nombresEstados = new ArrayList<>();
            int indexASeleccionar = -1;
            int i = 0;
            for (Estado e : listaEstados) {
                nombresEstados.add(e.getNombre());
                if (e.getId() == municipio.getIdEstado()) {
                    indexASeleccionar =  i;
                }
                i++;
            }
            jComboBox1.setModel(new DefaultComboBoxModel(nombresEstados.toArray()));
            tb_id.setText(municipio.getId() + "");
            tb_nombre.setText(municipio.getNombre());
            //Seleccionar estado correcto en combo
            jComboBox1.setSelectedIndex(indexASeleccionar);
            
        } else {
            dispose();
            //Mensaje de actualizacion exitosa
            JOptionPane.showMessageDialog(this, "No se pueden editar municipios ya que no existen estados", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcontenido = new javax.swing.JPanel();
        panelmunicipio = new javax.swing.JPanel();
        pnl_id = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tb_id = new javax.swing.JTextField();
        pnl_nombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tb_nombre = new javax.swing.JTextField();
        pnl_estado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelfooter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setTitle("Editar municipio");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelcontenido.setLayout(new javax.swing.BoxLayout(panelcontenido, javax.swing.BoxLayout.LINE_AXIS));

        panelmunicipio.setLayout(new javax.swing.BoxLayout(panelmunicipio, javax.swing.BoxLayout.PAGE_AXIS));

        pnl_id.setLayout(new javax.swing.BoxLayout(pnl_id, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("id");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_id.add(jLabel1);

        tb_id.setText(" ");
        tb_id.setMaximumSize(new java.awt.Dimension(300, 30));
        tb_id.setMinimumSize(new java.awt.Dimension(300, 30));
        tb_id.setPreferredSize(new java.awt.Dimension(300, 30));
        tb_id.setEnabled(false);
        pnl_id.add(tb_id);

        panelmunicipio.add(pnl_id);

        pnl_nombre.setLayout(new javax.swing.BoxLayout(pnl_nombre, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Nombre");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_nombre.add(jLabel2);

        tb_nombre.setMaximumSize(new java.awt.Dimension(300, 30));
        tb_nombre.setMinimumSize(new java.awt.Dimension(300, 30));
        tb_nombre.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_nombre.add(tb_nombre);

        panelmunicipio.add(pnl_nombre);

        pnl_estado.setLayout(new javax.swing.BoxLayout(pnl_estado, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Estado");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_estado.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox1.setAlignmentX(0.0F);
        jComboBox1.setMaximumSize(new java.awt.Dimension(300, 30));
        jComboBox1.setMinimumSize(new java.awt.Dimension(300, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_estado.add(jComboBox1);

        panelmunicipio.add(pnl_estado);

        panelcontenido.add(panelmunicipio);

        getContentPane().add(panelcontenido);

        panelfooter.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelfooter.setMinimumSize(new java.awt.Dimension(480, 35));
        panelfooter.setPreferredSize(new java.awt.Dimension(480, 35));
        panelfooter.setLayout(new javax.swing.BoxLayout(panelfooter, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 354, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 35, Short.MAX_VALUE)
        );

        panelfooter.add(jPanel1);

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panelfooter.add(btn_guardar);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        panelfooter.add(btn_cancelar);

        getContentPane().add(panelfooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //Validar que existan los dos datos
        if (tb_nombre.getText().length() > 0) {
            coordinador = new Coordinador();
            municipio.setNombre(tb_nombre.getText());
            Estado estado = listaEstados.get(jComboBox1.getSelectedIndex());
            municipio.setIdEstado(estado.getId());
            coordinador.updateMunicipio(municipio);
            BroadcastUtils.mensajeAServidorRemoto("Operacion");
            //Mensaje de actualizacion exitosa
            municipiosFrame.cargarMunicipios();
            dispose();
            JOptionPane.showMessageDialog(this, "Municipio actualizado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            //Mensaje de que la zona no es conocida
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelcontenido;
    private javax.swing.JPanel panelfooter;
    private javax.swing.JPanel panelmunicipio;
    private javax.swing.JPanel pnl_estado;
    private javax.swing.JPanel pnl_id;
    private javax.swing.JPanel pnl_nombre;
    private javax.swing.JTextField tb_id;
    private javax.swing.JTextField tb_nombre;
    // End of variables declaration//GEN-END:variables
}
