/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedistribuida.vista;

import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author iovanny
 */
public class Panel extends javax.swing.JFrame {

    Personas personas = new Personas();
    File file = null;
    Image img = null;

    /**
     * Creates new form Principal
     */
    public Panel() {
        initComponents();
        try {
            //System.out.println(System.getProperty("user.dir"));
            file = new File(System.getProperty("user.dir") + "/archivos/personas.png");
            img = ImageIO.read(file).getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            btnpersonas.setIcon(new ImageIcon(img));
            file = new File(System.getProperty("user.dir") + "/archivos/colonias.png");
            img = ImageIO.read(file).getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            btncolonias.setIcon(new ImageIcon(img));
            file = new File(System.getProperty("user.dir") + "/archivos/municipios.png");
            img = ImageIO.read(file).getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            btnmunicipios.setIcon(new ImageIcon(img));
            file = new File(System.getProperty("user.dir") + "/archivos/estados.png");
            img = ImageIO.read(file).getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            btnestados.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnpersonas = new javax.swing.JButton();
        btncolonias = new javax.swing.JButton();
        btnmunicipios = new javax.swing.JButton();
        btnestados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base Distribuida");
        setMaximumSize(new java.awt.Dimension(600, 100));
        setResizable(false);

        jPanel3.setMaximumSize(new java.awt.Dimension(600, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnpersonas.setText("Personas");
        btnpersonas.setMaximumSize(new java.awt.Dimension(150, 100));
        btnpersonas.setMinimumSize(new java.awt.Dimension(150, 100));
        btnpersonas.setPreferredSize(new java.awt.Dimension(150, 100));
        btnpersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonasActionPerformed(evt);
            }
        });
        jPanel3.add(btnpersonas);

        btncolonias.setText("Colonias");
        btncolonias.setMaximumSize(new java.awt.Dimension(150, 100));
        btncolonias.setMinimumSize(new java.awt.Dimension(150, 100));
        btncolonias.setPreferredSize(new java.awt.Dimension(150, 100));
        btncolonias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoloniasActionPerformed(evt);
            }
        });
        jPanel3.add(btncolonias);

        btnmunicipios.setText("Municipios");
        btnmunicipios.setMaximumSize(new java.awt.Dimension(150, 100));
        btnmunicipios.setMinimumSize(new java.awt.Dimension(150, 100));
        btnmunicipios.setPreferredSize(new java.awt.Dimension(150, 100));
        btnmunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmunicipiosActionPerformed(evt);
            }
        });
        jPanel3.add(btnmunicipios);

        btnestados.setText("Estados");
        btnestados.setMaximumSize(new java.awt.Dimension(150, 100));
        btnestados.setMinimumSize(new java.awt.Dimension(150, 100));
        btnestados.setPreferredSize(new java.awt.Dimension(150, 100));
        btnestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnestadosActionPerformed(evt);
            }
        });
        jPanel3.add(btnestados);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonasActionPerformed
        personas.setVisible(true);
    }//GEN-LAST:event_btnpersonasActionPerformed

    private void btncoloniasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoloniasActionPerformed
        Colonias colonias = new Colonias();
        colonias.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btncoloniasActionPerformed

    private void btnmunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmunicipiosActionPerformed
        Municipios municipios = new Municipios();
        municipios.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnmunicipiosActionPerformed

    private void btnestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnestadosActionPerformed
        Estados estados = new Estados();
        estados.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnestadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncolonias;
    private javax.swing.JButton btnestados;
    private javax.swing.JButton btnmunicipios;
    private javax.swing.JButton btnpersonas;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
