/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedistribuida.vista;

/**
 *
 * @author iovanny
 */
public class Verpersona extends javax.swing.JFrame {

    /**
     * Creates new form Agregarpersona
     */
    public Verpersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcontenido = new javax.swing.JPanel();
        panelpersona = new javax.swing.JPanel();
        id = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        nombre = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        apaterno = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbl_apaterno = new javax.swing.JLabel();
        amaterno = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lbl_amaterno = new javax.swing.JLabel();
        fecnac = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lbl_fecnac = new javax.swing.JLabel();
        genero = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lbl_genero = new javax.swing.JLabel();
        paneldatos = new javax.swing.JPanel();
        pnl_calle = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lbl_calle = new javax.swing.JLabel();
        pnl_cp = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        pnl_colonia = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        lbl_colonia = new javax.swing.JLabel();
        pnl_municipio = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        lbl_municipio = new javax.swing.JLabel();
        pnl_estado = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        pnl_zona = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lbl_zona = new javax.swing.JLabel();
        panelfooter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();

        setTitle("Ver persona");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelcontenido.setLayout(new javax.swing.BoxLayout(panelcontenido, javax.swing.BoxLayout.LINE_AXIS));

        panelpersona.setLayout(new javax.swing.BoxLayout(panelpersona, javax.swing.BoxLayout.PAGE_AXIS));

        id.setLayout(new javax.swing.BoxLayout(id, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("id");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel6.setName(""); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 20));
        id.add(jLabel6);

        lbl_id.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_id.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_id.setName(""); // NOI18N
        lbl_id.setPreferredSize(new java.awt.Dimension(300, 30));
        id.add(lbl_id);

        panelpersona.add(id);

        nombre.setLayout(new javax.swing.BoxLayout(nombre, javax.swing.BoxLayout.LINE_AXIS));

        jLabel14.setText("Nombre");
        jLabel14.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel14.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel14.setName(""); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 20));
        nombre.add(jLabel14);

        lbl_nombre.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_nombre.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_nombre.setName(""); // NOI18N
        lbl_nombre.setPreferredSize(new java.awt.Dimension(300, 30));
        nombre.add(lbl_nombre);

        panelpersona.add(nombre);

        apaterno.setLayout(new javax.swing.BoxLayout(apaterno, javax.swing.BoxLayout.LINE_AXIS));

        jLabel16.setText("Apellido paterno");
        jLabel16.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel16.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel16.setName(""); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 20));
        apaterno.add(jLabel16);

        lbl_apaterno.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_apaterno.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_apaterno.setName(""); // NOI18N
        lbl_apaterno.setPreferredSize(new java.awt.Dimension(300, 30));
        apaterno.add(lbl_apaterno);

        panelpersona.add(apaterno);

        amaterno.setLayout(new javax.swing.BoxLayout(amaterno, javax.swing.BoxLayout.LINE_AXIS));

        jLabel18.setText("Apellido materno");
        jLabel18.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel18.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel18.setName(""); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(200, 20));
        amaterno.add(jLabel18);

        lbl_amaterno.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_amaterno.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_amaterno.setName(""); // NOI18N
        lbl_amaterno.setPreferredSize(new java.awt.Dimension(300, 30));
        amaterno.add(lbl_amaterno);

        panelpersona.add(amaterno);

        fecnac.setLayout(new javax.swing.BoxLayout(fecnac, javax.swing.BoxLayout.LINE_AXIS));

        jLabel20.setText("Fecha de nacimiento");
        jLabel20.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel20.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel20.setName(""); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(200, 20));
        fecnac.add(jLabel20);

        lbl_fecnac.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_fecnac.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_fecnac.setName(""); // NOI18N
        lbl_fecnac.setPreferredSize(new java.awt.Dimension(300, 30));
        fecnac.add(lbl_fecnac);

        panelpersona.add(fecnac);

        genero.setLayout(new javax.swing.BoxLayout(genero, javax.swing.BoxLayout.LINE_AXIS));

        jLabel22.setText("Genero");
        jLabel22.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel22.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel22.setName(""); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(200, 20));
        genero.add(jLabel22);

        lbl_genero.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_genero.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_genero.setName(""); // NOI18N
        lbl_genero.setPreferredSize(new java.awt.Dimension(300, 30));
        genero.add(lbl_genero);

        panelpersona.add(genero);

        panelcontenido.add(panelpersona);

        paneldatos.setLayout(new javax.swing.BoxLayout(paneldatos, javax.swing.BoxLayout.PAGE_AXIS));

        pnl_calle.setLayout(new javax.swing.BoxLayout(pnl_calle, javax.swing.BoxLayout.LINE_AXIS));

        jLabel24.setText("Calle");
        jLabel24.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel24.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel24.setName(""); // NOI18N
        jLabel24.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_calle.add(jLabel24);

        lbl_calle.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_calle.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_calle.setName(""); // NOI18N
        lbl_calle.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_calle.add(lbl_calle);

        paneldatos.add(pnl_calle);

        pnl_cp.setLayout(new javax.swing.BoxLayout(pnl_cp, javax.swing.BoxLayout.LINE_AXIS));

        jLabel26.setText("C.P.");
        jLabel26.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel26.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel26.setName(""); // NOI18N
        jLabel26.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_cp.add(jLabel26);

        lbl_cp.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_cp.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_cp.setName(""); // NOI18N
        lbl_cp.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_cp.add(lbl_cp);

        paneldatos.add(pnl_cp);

        pnl_colonia.setLayout(new javax.swing.BoxLayout(pnl_colonia, javax.swing.BoxLayout.LINE_AXIS));

        jLabel28.setText("Colonia");
        jLabel28.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel28.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel28.setName(""); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_colonia.add(jLabel28);

        lbl_colonia.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_colonia.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_colonia.setName(""); // NOI18N
        lbl_colonia.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_colonia.add(lbl_colonia);

        paneldatos.add(pnl_colonia);

        pnl_municipio.setLayout(new javax.swing.BoxLayout(pnl_municipio, javax.swing.BoxLayout.LINE_AXIS));

        jLabel30.setText("Municipio");
        jLabel30.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel30.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel30.setName(""); // NOI18N
        jLabel30.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_municipio.add(jLabel30);

        lbl_municipio.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_municipio.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_municipio.setName(""); // NOI18N
        lbl_municipio.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_municipio.add(lbl_municipio);

        paneldatos.add(pnl_municipio);

        pnl_estado.setLayout(new javax.swing.BoxLayout(pnl_estado, javax.swing.BoxLayout.LINE_AXIS));

        jLabel32.setText("Estado");
        jLabel32.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel32.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel32.setName(""); // NOI18N
        jLabel32.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_estado.add(jLabel32);

        lbl_estado.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_estado.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_estado.setName(""); // NOI18N
        lbl_estado.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_estado.add(lbl_estado);

        paneldatos.add(pnl_estado);

        pnl_zona.setLayout(new javax.swing.BoxLayout(pnl_zona, javax.swing.BoxLayout.LINE_AXIS));

        jLabel34.setText("Zona");
        jLabel34.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel34.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel34.setName(""); // NOI18N
        jLabel34.setPreferredSize(new java.awt.Dimension(200, 20));
        pnl_zona.add(jLabel34);

        lbl_zona.setMaximumSize(new java.awt.Dimension(300, 30));
        lbl_zona.setMinimumSize(new java.awt.Dimension(300, 30));
        lbl_zona.setName(""); // NOI18N
        lbl_zona.setPreferredSize(new java.awt.Dimension(300, 30));
        pnl_zona.add(lbl_zona);

        paneldatos.add(pnl_zona);

        panelcontenido.add(paneldatos);

        getContentPane().add(panelcontenido);

        panelfooter.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelfooter.setMinimumSize(new java.awt.Dimension(480, 35));
        panelfooter.setPreferredSize(new java.awt.Dimension(480, 35));
        panelfooter.setLayout(new javax.swing.BoxLayout(panelfooter, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelfooter.add(jPanel1);

        btn_editar.setText("Editar");
        panelfooter.add(btn_editar);

        btn_eliminar.setText("Eliminar");
        btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelfooter.add(btn_eliminar);

        btn_cerrar.setText("Cerrar");
        panelfooter.add(btn_cerrar);

        getContentPane().add(panelfooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verpersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel amaterno;
    private javax.swing.JPanel apaterno;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JPanel fecnac;
    private javax.swing.JPanel genero;
    private javax.swing.JPanel id;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_amaterno;
    private javax.swing.JLabel lbl_apaterno;
    private javax.swing.JLabel lbl_calle;
    private javax.swing.JLabel lbl_colonia;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_fecnac;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_municipio;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_zona;
    private javax.swing.JPanel nombre;
    private javax.swing.JPanel panelcontenido;
    private javax.swing.JPanel paneldatos;
    private javax.swing.JPanel panelfooter;
    private javax.swing.JPanel panelpersona;
    private javax.swing.JPanel pnl_calle;
    private javax.swing.JPanel pnl_colonia;
    private javax.swing.JPanel pnl_cp;
    private javax.swing.JPanel pnl_estado;
    private javax.swing.JPanel pnl_municipio;
    private javax.swing.JPanel pnl_zona;
    // End of variables declaration//GEN-END:variables
}
